### ISSUE TITLE
April 3, 2019

### ISSUE THREAD

**Issue by lenaorobei** [magento/architecture#137]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥  (Recording](https://youtu.be/UCNATY5ZIfU)

**Comment by lenaorobei** [comment]
- **Magento Coding Standard Versioning** https://github.com/magento/architecture/pull/136 (5 min)

- **Discuss implementation and severity of new Magento Coding Standard rules** (15 min)

    - Proxies and interceptors MUST never be explicitly requested in constructors https://github.com/magento/magento-coding-standard/pull/59 by @maderlock 

    - Slow array SHOULD NOT be used in loop https://github.com/magento/magento-coding-standard/pull/72 by @larsroettig 

    - No try block detected when processing system resources https://github.com/magento/magento-coding-standard/pull/77 by @larsroettig

**Comment by joshuaadickerson** [comment]
- **PSR 14** more generally, using PSRs to standardize https://magentocommeng.slack.com/archives/C4YS78WE6/p1553709474019800

**Comment by buskamuza** [comment]
@melnikovi : adding an optional argument in constructor.
   * @akaplya : currently it's a MINOR change, we should not do such changes in Magento patch releases
   * @buskamuza : we should distinguish classes that have to be extended (because there is not way around it) and classes that can use composition (as intended). See also https://github.com/magento/devdocs/pull/4156
      * @larsroettig : there are many extensions that inherit from Magento core classes
