### ISSUE TITLE
Pool objects are named incorrectly in many places

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/architecture#154]
I just realized that in Magento we have too many classes named as "Pool", but not realizing [Object Pool pattern](https://en.wikipedia.org/wiki/Object_pool_pattern).

> The object pool pattern is a software creational design pattern that uses a set of initialized objects kept ready to use – a "pool" – rather than allocating and destroying them on demand. _A client of the pool will request an object from the pool and perform operations on the returned object. When the client has finished, it returns the object to the pool rather than destroying it; this can be done manually or automatically._

Here is quite a lot of examples that aren't mapping to this definition, specially to 2nd part of it:
> \Magento\SalesRule\Model\Validator\Pool
\Magento\Ui\DataProvider\Modifier\Pool
\Magento\Framework\Pricing\Adjustment\Pool
\Magento\Framework\View\Layout\Pool
\Magento\Framework\View\Layout\GeneratorPool
\Magento\Ui\Component\Control\ActionPool

I just listed few of them, but there are much more.

I think they should be renamed to "list" or something like that.

**Comment by buskamuza** [comment]
Yes. Known issue...
There are two things to address here:
1. Fix existing code. It is problematic because it's a breaking change. Especially with this kind of objects because usually they are extension points. The benefit from renaming is low compared to backward compatibility impact. So I would not recommend renaming. Doc blocks that explains that it's not a Pool pattern can be added if it makes sense.
2. How to avoid future Pool classes like this? Probably only ongoing education. As with any other best practice. I think there was a period when these Pool classes appeared, and after that it was discussed and people stopped doing this. So I hope the situation is better now.

**Comment by orlangur** [comment]
@ihor-sviziev,

> `\Magento\Framework\View\Layout\Pool`

Yep, this is a factory. Do we still not allow autogenerated factories in framework?

> `\Magento\Framework\View\Layout\GeneratorPool`

I don't see why this is not a pool.

We can add a test which would verify that any pool is added consciously (maybe for some other patterns too). Something similar to `<action` methods allowed in layout test.

**Comment by orlangur** [comment]
@buskamuza,

> Yes. Known issue...

> Fix existing code. It is problematic because it's a breaking change. Especially with this kind of objects because usually they are extension points. The benefit from renaming is low compared to backward compatibility impact. So I would not recommend renaming. Doc blocks that explains that it's not a Pool pattern can be added if it makes sense.

Well, this totally does not make sense to me. We need to have a deprecation and releasing policy lightweight enough so that it can be actually used, complemented with comprehensive automated tooling.

Any `*\Pool` name is poor anyway (just like `*\Collection` etc).

So, I would support @ihor-sviziev in picking better names for those classes. They can be deprecated in `2.4.0` and removed in `2.5.0`. Then let's try to embody this into life by covering any missing gaps in processes and/or tooling (such efforts can be reused later in similar initiatives).

**Comment by ihor-sviziev** [comment]
> So, I would support @ihor-sviziev in picking better names for those classes. They can be deprecated in 2.4.0 and removed in 2.5.0. Then let's try to embody this into life by covering any missing gaps in processes and/or tooling (such efforts can be reused later in similar initiatives).

Why can’t it be done in patch release?
I’d prefer to:
- create new class with correct name (replace Pool to List for incatance), 
- move all code from Pool to List class
- extend Pool from List class
- mark Pool as deprecated with description why and link to correct class

That would be backward compatible change

**Comment by buskamuza** [comment]
@ihor-sviziev , ok. Can you submit the same as a PR, so it will be stored in the repo as a proposal?

**Comment by vkublytskyi** [comment]
Agree that name "Pool" is abused and was chosen not correctly. But this is not a strong reason to introduce such serious backward incompatible changes.

If check implementation of all mentioned classes then List is also would be an incorrect definition of what some of them are. So I would prefer to avoid similar changes in many places and consider each class in case by case basis.

Meanwhile, as @buskamuza already mentioned, pools are not recommended approach now (yet sometimes most straight forward solution) so any new case should be strongly justified during code review. The same for any abused words like Manager, Service, Util, Helper etc.

**Comment by larsroettig** [comment]
> > So, I would support @ihor-sviziev in picking better names for those classes. They can be deprecated in 2.4.0 and removed in 2.5.0. Then let's try to embody this into life by covering any missing gaps in processes and/or tooling (such efforts can be reused later in similar initiatives).
> 
> Why can’t it be done in patch release?
> I’d prefer to:
> 
> * create new class with correct name (replace Pool to List for instance),
> * move all code from Pool to List class
> * extend Pool from List class
> * mark Pool as deprecated with description why and link to correct class
> 
> That would be backward compatible change

Sounds very good tumps up for the proposal?

**Comment by paliarush** [comment]
We need to keep in mind that with the proposed refactoring new classes cannot be marked as `@api` until 2.4 anyway since this is a minor change.

**Comment by orlangur** [comment]
@paliarush,

> mark Pool as deprecated with description why and link to correct class

Can we add deprecations in a patch release?

**Comment by ihor-sviziev** [comment]
Hi @buskamuza,
I'll create PR little bit later.

BTW - how come new Poll classes still created? 
https://github.com/magento/magento2/commit/61f4037ea7ac50d676cdedaa835e16b50ebad2c5#diff-655ad2be93e58cb0cf836a315c97eb04R13
Can it be removed before including into release?

**Comment by buskamuza** [comment]
@orlangur , yes, we can add deprecations in patch releases.

**Comment by maghamed** [comment]
There are just 2 hard problems in Software development: Naming and Cache Invalidation and here we are facing one of those.
Even so that some names are given to Magento classes not properly, we can't easily resolve this problem applying some patter, like Pool to List (you can put any other name here).

Moreover, such classes like `\Magento\Framework\View\Layout\GeneratorPool` or `\Magento\Ui\DataProvider\Modifier\Pool` are quite similar to the general idea of Object Pool pattern (at least the `Pool` name much better describes their responsibility than `List`).

So, each and every case should be considered and resolved independently out of others. 

Another issue is Backward Compatibility, which we must respect above most of the improvements. 
In Magento 2 Backward Compatibility is more important than code niceness. 
Introducing another class and making an existing class inherit from it - is not a robust solution.

Moreover, we may have a problem when 3PDs and extensions are extending and customizing constructor dependency of Pool objects, while Magento code started to rely on a new ones - List

```
    /**
     * @param ScheduledStructure\Helper $helper
     * @param ConditionFactory $conditionFactory
     * @param \Psr\Log\LoggerInterface $logger
     * @param array $generators
     */
    public function __construct(
        ScheduledStructure\Helper $helper,
        ConditionFactory $conditionFactory,
        \Psr\Log\LoggerInterface $logger,
        array $generators = null
    ) {
        $this->helper = $helper;
        $this->conditionFactory = $conditionFactory;
        $this->logger = $logger;
        $this->addGenerators($generators);
    }
``` 

Here we can get a mess and lose some customizations.
So, I would rather prefer not doing this, and go with the safest approach providing PHP Doc comment instead.
