### ISSUE TITLE
May 29, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#165]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

No recording due to technical difficulties.

**Comment by kalpmehta** [comment]
From Imagine Dev Exchange:
Implicitly escape HTML/JS code to prevent XSS vulnerabilities (15 min)

https://twitter.com/kalpmehta/status/1129121495760789504

**Comment by sivaschenko** [comment]
Search Result Interfaces https://github.com/magento/magento2/pull/20181 (15min)

**Comment by sivaschenko** [comment]
Add a module manager to the Magento Framework API https://github.com/magento/magento2/pull/18748 (15min)

**Comment by kokoc** [comment]
Webhooks https://github.com/magento/architecture/pull/169 (20 min)

**Comment by navarr** [comment]
Introduce MessageFormatter syntax and new rules for Phrases #170 (15 min)

**Comment by knowj** [comment]
Cron proposal #171 (15min)

**Comment by melnikovi** [comment]
_Escaping HTML/JavaScript_
@kalpmehta 
* escape getParams, getRequest
* don't allow to save HTML where you shouldn't have HTML

@AlexMaxHorkun 
* the best practice is to do escaping on output

@knowj 
* should we have better input validation?
* content security policy?

@kokoc 
* CSP is in backlog for 2.4

CSP is in backlog for 2.4. Need to create proposal for implicit output escaping. @melnikovi sync with @maghamed on imagine discussion and with @buskamuza on templates generation idea cons.

_Search Result Interfaces_
@kokoc 
* what is the reason to provide empty implementations?

Approved PR. Need to create separate issue to introduce code generation for these classes.

_Add module manager to the Magento Framework API_
@navarr 
* need to enable/disable some functionality depending on whether particular module exists.
* hard to manage modules if we have hard dependencies

@antonkril 
* trying to get away from soft dependencies, because they are hard to manage. Move towards hard dependencies.
* need to understand trade off of having soft dependencies
* for now it's ok to introduce this interface

@melnikovi 
* remove @api annotation in 2.3-develop branch and introduce in 2.4-develop

Ok to introduce this interface. Remove @api annotation in 2.3-develop branch and introduce in 2.4-develop.

_Webhooks_
Review proposal offline.
