### ISSUE TITLE
June 5, 2019

### ISSUE THREAD

**Issue by lenaorobei** [magento/architecture#174]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Recording: TBD

**Comment by sivaschenko** [comment]
https://github.com/magento/magento2/pull/19308 (15 mins)

**Comment by lenaorobei** [comment]
Contract for JSON encoding/decoding https://github.com/magento/architecture/pull/161 (15 min)

**Comment by Vinai** [comment]
What time is the meeting?

**Comment by lenaorobei** [comment]
@Vinai 10:30am CST/CDT

**Comment by paliarush** [comment]
SVC and optional constructor arguments.

**Comment by vzabaznov** [comment]
Advanced JS bundling (15 min), link - TBD

**Comment by pdohogne-magento** [comment]
Gaps in SVC coverage (https://github.com/magento/architecture/pull/175)
- Type annotations (5 min)
- Traits (5 min)
- Visibility (1 min)
- Class inheritance (5-10 min)

**Comment by irenelagno** [comment]
Review  SVC policy for adding optional argument for method in the  @api class:
https://github.com/magento/devdocs/pull/4676/files 
see: https://github.com/magento/magento2ce/commit/58d8196619b23f3fe8cb6804470fce9bdfd046aa

**Comment by orlangur** [comment]
@irenelagno https://github.com/magento/magento2ce/ is not publicly accessible.

**Comment by Vinai** [comment]
Can maybe JSON encoding/decoding be discussed a bit earlier during the meeting rather than later, because I might have a hard stop at 11am?

**Comment by pdohogne-magento** [comment]
@orlangur It's an example of a new commit that adds an optional method argument

**Comment by melnikovi** [comment]
_Contract for JSON encoding/decoding_
@Vinai 
* wrapping json_encode/json_decode makes sense
* adding optional argument is ok
* remove SerializerInterface

@melnikovi 
* we recommend to use concrete implementation instead of SerializerInterface

@maghamed 
* having exception thrown is more evident

@antonkril 
* don't force people to use SerializerInterface or implementations instead of PHP functions

Review offline and comment.

_Replaced ArrayInterface with OptionSourceInterface_
@sivaschenko 
* public PR

@melnikovi 
* deliver to 2.4

Deliver to 2.4 and remove interface

_SVC and optional constructor arguments_
@paliarush 
* allow adding optional parameter to @api classes except super types

@maghamed 
* can have a tool that would move hidden dependencies to constructor

Get more feedback from the community.

_Gaps in SVC coverage_
@melnikovi 
* check annotation, param types, traits, class inheritance

Accept PR.

_Are we going to make SVC public_

Make it public.

**Comment by maghamed** [comment]
Video recording - https://www.youtube.com/watch?v=ebHY_Rb1X0I
