### ISSUE TITLE
Bug or feature - dashes are not allowed in store codes

### ISSUE THREAD

**Issue by tylerssn** [magento/architecture#184]
In Magento 2.2 dashes are not allowed in store codes. If you attempted to update a store code with a dash an error is thrown:

> The store code may contain only letters (a-z), numbers (0-9) or underscore (_), and the first character must be a letter.

Was this intentional? What negative impact could come from allowing dashes?

**Comment by orlangur** [comment]
Where they allowed before?

**Comment by tylerssn** [comment]
In Magento 1, yes.

**Comment by orlangur** [comment]
In Magento 2.0 and 2.1 I mean :) This is for consistency - for filenames there is a convention also to use dashes only but it is not enforced.

**Comment by tylerssn** [comment]
Right, I assume the behavior is the same throughout each 2.* version. 

My question is do dashes actually break anything? We're wrapping up a M1->M2 migration and would like to leave the store codes as-is. I can live with building a plugin to for my one-off case if I have to, but would rather not :)

**Comment by orlangur** [comment]
It's a good time to bring some consistency ;)

Just convert all dashes to underscores during migration.

**Comment by tylerssn** [comment]
Is there any documentation regarding why this change was made? Admittedly, I'm doing my best to avoid having to crawl through third-party extensions to ensure that none of them use the old store code (such as Dotdigital in email campaigns).

My understanding is that it's common practice in M1 to use language codes as your store view code - which is what I have done here. We have `fr-ca` for Canadian French. It's likely that other M1 applications that will be migrating to M2 have this same practice implemented.

**Comment by orlangur** [comment]
I'm not aware of any such documentation. `fr_ca` should work just fine.

> It's likely that other M1 applications that will be migrating to M2 have this same practice implemented.

Please report in https://github.com/magento/data-migration-tool if store codes are not converted automatically to avoid dashes.

**Comment by paliarush** [comment]
Agree with @orlangur, this can be easily mitigated with data migration tool.

**Comment by davidverholen** [comment]
I would like to reopen this discussion because of reasons ;)

Magento has a setting to add store codes to the url to determine the current store.
This setting makes sense to have an easy multistore setup with localized urls.

Best practice is to have urls like
<base_url>/en-us
<base_url>/en-uk

This could be easily accomplished if dashes in store codes would be allowed.

From a current project I also know that this does not break anything, but makes it extremely easy to have a, multistore setup with localized urls  (by having "Add Store Code to Urls" enabled and have store codes like en-us and en-uk)

So while this is not a bug, it should be discussed here, if this is not a change worth implementing.
As far as I have seen there are just 2 places in the core, where they are validated. So it would be a very non invasive change with a huge value behind it

**Comment by davidverholen** [comment]
ok I cannot reopen it here apparently, @paliarush @orlangur what do you think?

**Comment by orlangur** [comment]
@davidverholen nice catch, I never liked underscores myself and especially looking at https://support.google.com/webmasters/answer/76329?hl=en I would rather forbid underscores for consistency.

For example, I insisted on convention to use dashes only in filenames, but it's still not enforced.

So, I'm all for allowing dashes.

Let's wait for @paliarush, I have no rights to reopen as well.

**Comment by Nolwennig-Jeulin** [comment]
Hi all,

sorry for excavate subject but, it's possible to re-open and work on this ? 

So, while I use this module: https://github.com/opengento/magento2-store-path-url (see : https://github.com/magento/architecture/issues/514)
