### ISSUE TITLE
July 31, 2019

### ISSUE THREAD

**Issue by cpartica** [magento/architecture#216]
Please add your topic as a comment to the issue. Use following format:
Topic description and link to PR, if any (duration in min)

🎥 [Recording](https://youtu.be/AjwiE5meM7M)

**Comment by cpartica** [comment]
Introduction of url route validator Magento\Framework\Url\RouteValidator https://github.com/magento/architecture/pull/215 10 min

**Comment by buskamuza** [comment]
Add `@spi` annotation (https://github.com/magento/architecture/pull/217) - 20min

**Comment by melnikovi** [comment]
Composer performance 15 min

**Comment by buskamuza** [comment]
* SPI
   * @maghamed : it will add more confusion. Not many people understand difference between API and SPI
   * @maghamed : What will the transition period look like?
* URl validator
  * introduce a new FW class that validates both absolute and relative URLs, deprecate new one
  * @kandy : add definition of what is a valid URL route. Maybe it makes sense to implement it from scratch instead of using ZF?
  @AlexMaxHorkun : should we add XSS protection to the URL validation?
* Composer performance:
   * @paliarush : the parallel download plugin didn't work in Vagrant DevBox some time ago
   * Piotr Siejczuk : the parallel plugin helped a lot
   * @paliarush , @pdohogne-magento : `composer.lock` depends on the environment it's generated in
