### ISSUE TITLE
September 11, 2019

### ISSUE THREAD

**Issue by paliarush** [magento/architecture#265]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/hMXxXCrklwQ)

**Comment by paliarush** [comment]
Versioning in GraphQL: https://github.com/magento/architecture/pull/263 (5-10 min)

**Comment by lenaorobei** [comment]
Single mutation for adding products to cart + wishlist https://github.com/magento/architecture/pull/256 (10 min)

**Comment by buskamuza** [comment]
Code style for GraphQL schema (https://github.com/magento/architecture/issues/269) (5min)

**Comment by arhiopterecs** [comment]
Reduce q-ty of error reports created in <magento_root>/var/report [#271](https://github.com/magento/architecture/pull/271)(10 min)

**Comment by prabhuram93** [comment]
Graphql product filters https://github.com/magento/architecture/pull/272 (10 - 15 min)

**Comment by melnikovi** [comment]
Database compatibility for declarative schema https://github.com/magento/architecture/pull/264 (15 min)

**Comment by buskamuza** [comment]
* Versioning in GraphQL
   * @paliarush : we may go back to original (non-versioned name later, e.g. in 5 years)
   * Add more details, to make the rules clear for fields, types, etc.
* Single mutation for adding products to cart + wishlist
   * @irenelagno : does it support "file" as an option? @akaplya : yes, as entered option.
   * @buskamuza : why do we need `base64_encode`? @akaplya : it's just an id, in the future it can be replaced with UUID. Client can get list of option ids with labels from the server
   * @kandy : can we add signature to ids? @akaplya , probably we can, we can look at this in the next iteration.
* Reduce q-ty of error reports created in <magento_root>/var/report
   * Add recommendations, which we can convert to guidelines
   * Consider lightweight DB as a storage
   * Consider logging everything in one file?
* Graphql product filters
   * @paliarush : it will not solve the cache regeneration problem entirely because the attributes are necessary for displaying the product
   * Add a real scenario to go through and understand which queries are necessary. Possible scenarios are: product listing page with layered navigation, product page.
   * There is still a problem with many attributes "spoiling" the schema on the top level
   * @paliarush : include metadata in aggregations response looks useful
