### ISSUE TITLE
September 18, 2019

### ISSUE THREAD

**Issue by lenaorobei** [magento/architecture#273]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/nUO2Xiw0v3A)

**Comment by paliarush** [comment]
GraphQL custom attributes container https://github.com/magento/architecture/pull/282 (10 min)

**Comment by buskamuza** [comment]
* GraphQL custom attributes container
   * @kandy : is it possible to limit list of returned attributes? @paliarush : all visible attributes will be returned, there is no way to limit further.
   * @kandy : why "custom_attributes"? @paliarush : same name is used in REST.
   * @akaplya : introduce type? @paliarush : talk to PWA team to clarify if it's necessary.
   * @buskamuza : please add more details about scenarios being covered. How to distinguish attributes that should be displayed in product listing vs on product details page.
   * @paliarush : should we include attribute metadata in the response? @akaplya : it's inefficient, because metadata can be cached separately.

**Comment by buskamuza** [comment]
* Changes in product pricing GraphQL schema (https://github.com/magento/architecture/pull/278)
   * ✅ looks good
