### ISSUE TITLE
September 25, 2019

### ISSUE THREAD

**Issue by tariqjawed83** [magento/architecture#290]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/gD7i9q7JF9w)

**Comment by tariqjawed83** [comment]
Import CSV Data / files into Magento using Async Bulk API,
https://github.com/magento/architecture/pull/270

**Comment by ihor-sviziev** [comment]
Would like to discuss following issue, but not sure if I could join https://github.com/magento/magento2/pull/24711
I tried to highlight it in issue descriptoin

**Comment by lenaorobei** [comment]
- No imports from static tests namespaces https://github.com/magento/magento-coding-standard/issues/142
- Do not use `in_array` https://github.com/magento/magento-coding-standard/issues/143

**Comment by AlexMaxHorkun** [comment]
BatchResolverInterface for GraphQL https://github.com/magento/architecture/pull/293 (15 min)

**Comment by melnikovi** [comment]
Compatibility of declarative schema with different databases https://github.com/magento/architecture/pull/264 15 min
Backwards compatibility policy for JavaScript 10 min

**Comment by paliarush** [comment]
Multi-device support for customer cart in GraphQL https://github.com/magento/architecture/pull/288 5 min

**Comment by buskamuza** [comment]
* No imports from static tests namespaces
   * @buskamuza : maybe prohibit any `Tests` import in application files?
* Do not use `in_array`
   * @AlexMaxHorkun : what to do with arrays of objects?
   * @buskamuza : we need measurements (including time and memory consumption). Maybe it should be just a recommendation
* Deprecate result factories in favor of one generic
   * @buskamuza : generic factory doesn't declare return type (it's generic).
   * With good objects decomposition for action controllers it should not be a problem to inject a specific factory because only one type of result factory should be needed
   * @buskamuza : from described options, option 1 (inject factory in constructor) should be a recommended way
   * @paliarush : some of the result factories are auto-generated, so we can't deprecated them
* BatchResolverInterface for GraphQL
   * Looks interesting. Let's review the proposal and the prototype offline
* Remove from JS BC guidelines: "Changed event ordering" as a MAJOR change.
   * @paliarush : it would be good to look at examples. Maybe there use cases where changing order of events is a breaking change
   * @buskamuza : ok to remove, but let's sync with @DrewML and author of the item
* Compatibility of declarative schema with different databases
   * @akaplya : to review the proposal, add link to schema standard, propose changes to the interface or describe vision for new interfaces
   * @buskamuza : cover BC question. Describe how places that use current DB adapter should be changed (if they need to).
   * @paliarush : make proposal more generic, not only about declarative schema?
