### ISSUE TITLE
 October 02, 2019 

### ISSUE THREAD

**Issue by larsroettig** [magento/architecture#302]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/iH8_Gk4ZTJw)

**Comment by larsroettig** [comment]
MYSQL investigation on the removal of dependency on Auto_Increment 
https://github.com/magento/architecture/pull/301 (15 min)

**Comment by paliarush** [comment]
Multi-device support for customer cart in GraphQL #288 (5 min)

**Comment by paliarush** [comment]
GraphQL schema for store pickup https://github.com/magento/architecture/pull/304

**Comment by paliarush** [comment]
GraphQL directives for attributes metadata https://github.com/magento/architecture/pull/299 (5 min)

**Comment by paliarush** [comment]
GraphQL schema for product reviews https://github.com/magento/architecture/pull/298 (5 min)

**Comment by paliarush** [comment]
GraphQL schema for product compare https://github.com/magento/architecture/pull/305 (5 min)

**Comment by buskamuza** [comment]
* MySQL 8 auto_increment
   * @akaplya : use sequence table to generate ID instead of relying on auto-generated IDs
   * @kandy : cache can be enabled after the auto_increment is retrieved
   * @akaplya : `SELECT MAX(id) FROM table` is not reliable and should not be used
   * @maghamed : implement disabling cache and run tests to make sure this fixes the problem with MySQL 8. Stepan: this might be not the only issue
* Multi-device support for customer cart in GraphQL
   * @jedmao : why to have a separate mutation for retrieving new cart?
   * @kandy : B2B has multiple carts
* GraphQL schema for store pickup - looks ok
* GraphQL directives for attributes metadata
   * @kandy : directive can't provide options
